name: Trigger auto deployment for dg7zltwcsdlfoms-apiii

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dg7zltwcsdlfomsregistry.azurecr.io/devguidebackendapi:v1/**'
    - '.github/workflows/dg7zltwcsdlfoms-apiii-AutoDeployTrigger-b1d0c358-727d-473d-8c0e-5d6b15c3806f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DG7ZLTWCSDLFOMSAPIII_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DG7ZLTWCSDLFOMSAPIII_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DG7ZLTWCSDLFOMSAPIII_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}dg7zltwcsdlfomsregistry.azurecr.io/devguidebackendapi:v1 
          registryUrl: dg7zltwcsdlfomsregistry.azurecr.io
          registryUsername: ${{ secrets.DG7ZLTWCSDLFOMSAPIII_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DG7ZLTWCSDLFOMSAPIII_REGISTRY_PASSWORD }}
          containerAppName: dg7zltwcsdlfoms-apiii
          resourceGroup: mongo-devguide-rg
          imageToBuild: dg7zltwcsdlfomsregistry.azurecr.io/dg7zltwcsdlfoms-apiii:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


